### ISSUE TITLE
serial_for_arduinoコンポーネントについて

### ISSUE THREAD

**Issue by Nobu19800** [TaskManagingSystem/task-managing-system#4]
serial_for_arduinoコンポーネントで、COMポートが「COM3」とソースコードに直接書いており変更できませんが、これはコンフィギュレーションパラメータで変更できるようにしておいた方が使いやすいと思います。

**Comment by Natto133** [comment]
issueありがとうございます。
コンフィグレーション変数にcom_portを追加し、対応しました。
